// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleInfo } from "./RoleInfo";

/**
 * BridgeV1 envelope 的 `event` 字段承载. 19 个变体, spec §3.2.
 *
 * Serde 表示: `{ kind: "roleTurn", role_id: "...", content: "...", is_complete: true }`
 * —— `kind` 区分变体, 字段名 camelCase (rust 字段名原样 snake_case 通过
 * serde 在序列化时按需 rename; 此处 variant 名 rename_all = camelCase,
 * 字段名保持 snake_case 与 `ChatEvent` 一致便于 round-trip).
 */
export type BridgeEventV1 = { "kind": "roleTurn", role_id: string, content: string, is_complete: boolean, } | { "kind": "status", message: string, } | { "kind": "prompt", icon: string, role_id: string, model_id: string, } | { "kind": "paused", reason: string, } | { "kind": "resumed" } | { "kind": "roundStarted", round: number, } | { "kind": "roundEnded", round: number, } | { "kind": "roleStarted", role_id: string, detail: string, } | { "kind": "roleFinished", role_id: string, detail: string, } | { "kind": "delegateStarted", from_role: string, to_role: string, task: string, sub_id: string, } | { "kind": "delegateFinished", from_role: string, to_role: string, status: string, summary: string, sub_id: string, } | { "kind": "done" } | { "kind": "error", message: string, } | { "kind": "roleList", roles: Array<RoleInfo>, } | { "kind": "contextCleared" } | { "kind": "sessionInfo", task_id: string, state: string, turn: number, roles: Array<RoleInfo>, } | { "kind": "toolUse", role_id: string, tool_name: string, args: string, } | { "kind": "toolResult", role_id: string, tool_name: string, result: string, } | { "kind": "toolError", role_id: string, tool_name: string, error: string, };
