// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BridgeCapabilities } from "./BridgeCapabilities";
import type { BridgeEventV1 } from "./BridgeEventV1";

/**
 * BridgeV1 envelope —— editor / web frontend 唯一对外契约（spec §3.2）。
 *
 * 字段顺序按 spec §3.2：`schema_version` → `session_id` → `workspace_id?` → `event` → `capabilities?`。
 * 可选字段用 `skip_serializing_if = "Option::is_none"`，让 envelope 在 workspace 无关的
 * standalone UI 场景下保持最小化 JSON 形态。
 *
 * 序列化示例：
 * ```json
 * {
 *   "schemaVersion": 1,
 *   "sessionId": "<editor uuid>",
 *   "workspaceId": "<opt>",
 *   "event": { "kind": "roleTurn", "roleId": "pm", ... },
 *   "capabilities": { "images": true, "subsession": true, ... }
 * }
 * ```
 */
export type BridgeV1Envelope = { 
/**
 * 协议 major 版本。当前 = 1；breaking change = major + 1。
 */
schema_version: number, 
/**
 * editor 持久 UUID（外部传入，bridge 不生成）。
 */
session_id: string, 
/**
 * editor workspace 切片（可空，editor route 决定）。
 */
workspace_id: string | null, 
/**
 * 具体事件 —— 见 [`BridgeEventV1`]。
 */
event: BridgeEventV1, 
/**
 * spawn 时 caller 提供的 capability flags；每次 envelope 都冗余带，方便消费方
 * 单条解析就能完成 capability 协商（spec §5.2）。
 */
capabilities: BridgeCapabilities | null, };
