// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * BridgeV1 capability 协商位。spec §3.2 + §5.2。
 *
 * 序列化形态（`rename_all = "camelCase"`）：
 * ```json
 * { "images": true, "subsession": true, "selfLoop": false, "swarm": false, "roleGraph": false }
 * ```
 */
export type BridgeCapabilities = { 
/**
 * 支持图片附件多模态消息（`latte_ai::models::ContentPart::Image`）。
 */
images: boolean, 
/**
 * 支持 delegate subsession 流（`BridgeEventV1::Delegate{Started,Finished}` + `subsession_store`）。
 */
subsession: boolean, 
/**
 * 支持 self-loop AI 自调试循环（仅 standalone ui 启用）。
 */
selfLoop: boolean, 
/**
 * 支持 swarm 群聊会话（编辑器独有）。
 */
swarm: boolean, 
/**
 * 支持 role_graph 角色 × 工具代码关系图。
 */
roleGraph: boolean, };
