// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 角色 / 工具元信息。与 `latte_agent_core::controller::RoleInfo` 同形,
 * 通过 `From` 在 convert 层完成转换 —— 这样 bridge 端不必依赖 controller
 * 内部实现细节, 仅在 convert.rs 处单向耦合。
 */
export type RoleInfo = { 
/**
 * 角色唯一 ID, e.g. `"pm"` / `"programmer"` / `"reviewer"`.
 */
id: string, 
/**
 * 人类可读角色名, e.g. `"Project Manager"`.
 */
name: string, 
/**
 * 单字符或 emoji 图标, UI 用作头像或装饰前缀.
 */
icon: string, };
