// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoleInfo } from "./RoleInfo";

/**
 * 启动 / `/info` 等场景下的会话元信息。与 `BridgeEventV1::SessionInfo` 变体共享字段，
 * 单独作为 DTO 暴露便于 editor 在握手指令之外按需查询。
 */
export type SessionInfo = { 
/**
 * 任务标识（与 `StoredSession::session_id` 同源）。
 */
taskId: string, 
/**
 * 生命周期状态字符串。`"created" | "running" | "paused" | "finished" | "failed"`。
 */
state: string, 
/**
 * 当前轮次（multi-role mode 才有意义）。
 */
turn: number, 
/**
 * 当前会话可用角色列表。
 */
roles: Array<RoleInfo>, };
