//! Round and turn types for discussion orchestration.

use serde::{Deserialize, Serialize};

/// How agents take turns in a discussion round.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TurnOrder {
    /// Fixed sequence: [pm, dev, qa] repeats each round.
    Fixed(Vec<String>),
    /// Round-robin with optional skip for abstainers.
    RoundRobin,
    /// Moderator (named agent) decides who speaks next.
    Moderated { moderator: String },
    /// All agents speak concurrently within a step.
    Parallel(Vec<String>),
}

impl Default for TurnOrder {
    fn default() -> Self {
        Self::Fixed(Vec::new())
    }
}

/// A single turn: one agent speaks.
#[derive(Debug, Clone)]
pub struct Turn {
    /// The agent name.
    pub agent: String,
    /// Prompt injected before this agent's turn.
    pub prompt: String,
    /// Expected role for validation.
    pub role_id: Option<String>,
}

/// Record of a completed turn.
#[derive(Debug, Clone)]
pub struct TurnRecord {
    /// Agent name that spoke.
    pub agent: String,
    /// Agent's role id.
    pub role_id: String,
    /// The response content.
    pub response: String,
    /// Round number (0-indexed).
    pub round: usize,
    /// Step id within the round.
    pub step_id: String,
    /// Turn number within the step.
    pub turn_number: usize,
}

/// A round: one pass through the workflow steps.
#[derive(Debug, Clone)]
pub struct Round {
    /// Round number (0-indexed).
    pub number: usize,
    /// Turns completed in this round.
    pub turns: Vec<TurnRecord>,
    /// Whether consensus was reached after this round.
    pub consensus_reached: bool,
    /// Summary of the round (generated by optional summarizer).
    pub summary: Option<String>,
}

impl Round {
    pub fn new(number: usize) -> Self {
        Self {
            number,
            turns: Vec::new(),
            consensus_reached: false,
            summary: None,
        }
    }

    /// Add a completed turn to this round.
    pub fn record(&mut self, record: TurnRecord) {
        self.turns.push(record);
    }

    /// Concatenate all agent responses in this round.
    pub fn transcript(&self) -> String {
        self.turns
            .iter()
            .map(|t| format!("[{}] {}\n", t.agent, t.response))
            .collect()
    }
}

/// Result of a complete discussion.
#[derive(Debug, Clone)]
pub struct DiscussionResult {
    /// All rounds.
    pub rounds: Vec<Round>,
    /// Whether consensus was reached.
    pub consensus_reached: bool,
    /// The consensus vote breakdown (if voting was used).
    pub votes: Option<VoteResult>,
    /// Final summary.
    pub summary: Option<String>,
    /// Total token usage across all agents.
    pub total_usage: latte_ai::models::TokenUsage,
}

/// Result of a vote/consensus check.
#[derive(Debug, Clone, Default)]
pub struct VoteResult {
    /// Per-agent votes.
    pub votes: Vec<AgentVote>,
    /// Whether consensus was reached.
    pub consensus: bool,
    /// Which option won (if any).
    pub winner: Option<String>,
    /// Agreement percentage (0.0–1.0).
    pub agreement: f64,
}

/// A single agent's vote.
#[derive(Debug, Clone)]
pub struct AgentVote {
    pub agent: String,
    pub position: String,
    pub confidence: f64,
    pub reasoning: String,
}
